In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
df = pd.read_csv('datasets/hospitalizaciones_train.csv')

### ¿Qué tipo de datos tengo?

* Cuantitativos 
    - Discretos: Available Extra Rooms in Hospital, staff_available, Visitors with Patient, 
    - Continuos: Admission_Deposit
* Cualitativos
    - Nominales: Department, Ward_Facility_Code, doctor_name,patientid, gender, Type of Admission, health_conditions
    - Ordinales: Severity of Illness, Age
    - Binario: Insurance
* Variable a predecir
    - Stay (in days)

# Preprocesamiento

In [ ]:
X=df.iloc[:,0:-1]
# columna que expresa si la estadia es alrga o no (0 = no y 1 = si)
y= np.where(df.iloc[:,-1]<=8,0,1)

In [4]:
X.drop(['patientid'],axis=1,inplace=True)#''Available Extra Rooms in Hospital','staff_available',gender','Insurance','Ward_Facility_Code''doctor_name','Admission_Deposit'

## Tranformo y segun lo pedido.

### Columnas para transformacion

In [5]:
#columnas nominales
ohe_col=['Department', 'Ward_Facility_Code','doctor_name', 'Age', 
     'Type of Admission', 'health_conditions','gender']
#columna ordinal
ord=['Severity of Illness']
#columnas binarias
binar = ['Insurance']

### Ordinal

In [6]:
gravedad_enfer = ['Extreme','Moderate','Minor']

In [7]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[gravedad_enfer],dtype='uint8')

In [8]:
X['Severity of Illness'] = oe.fit_transform(X[['Severity of Illness']])

## LaberlBinarizer

In [9]:
X['Insurance'] = X['Insurance'].map({'Yes':1,'No':0})

## OneHotEncoder

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(dtype='uint8')
# ohe.fit_transform(df_copy[['Department']]).toarray()

In [11]:
for col in ohe_col:
    df_dep = pd.DataFrame(ohe.fit_transform(X[[col]]).toarray(),columns=[col+'_'+str(ohe.categories_[0][i])for i in range(len(ohe.categories_[0]))])
    X = pd.concat([X,df_dep],axis=1)
    X.drop(col,axis=1,inplace=True)

In [12]:
X

,Available Extra Rooms in Hospital,staff_available,Severity of Illness,Visitors with Patient,Insurance,Admission_Deposit,Department_TB & Chest disease,Department_anesthesia,Department_gynecology,Department_radiotherapy,...,Type of Admission_Urgent,health_conditions_Asthama,health_conditions_Diabetes,health_conditions_Heart disease,health_conditions_High Blood Pressure,health_conditions_None,health_conditions_Other,gender_Female,gender_Male,gender_Other
0,4,0,0,4,1,2966.408696,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1,4,2,2,2,0,3554.835677,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
2,2,8,0,2,1,5624.733654,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
3,4,7,1,4,0,4814.149231,0,0,1,0,...,1,0,0,0,0,1,0,1,0,0
4,2,10,1,2,0,5169.269637,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409995,1,1,2,3,1,3902.291076,0,0,1,0,...,0,1,0,0,0,0,0,1,0,0
409996,5,5,0,4,0,4771.995223,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
409997,4,9,2,4,1,3816.994210,0,0,1,0,...,0,1,0,0,0,0,0,1,0,0
409998,10,10,1,2,1,3841.577491,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
409999,3,0,2,8,1,4329.046412,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0

agrego columna 'estadia_larga' donde si=1 y no =0

In [13]:
X['estadia_larga'] = y

Exporto el dataframe transformado

In [14]:
X.to_csv('datasets_modelo/df_trans_train.csv',index=False)